const stages=[
['ROOKIE',100,1],['BEGINNER',500,3],['TRAINEE',2500,8],['FIGHTER',12000,20],['IRON FIGHTER',60000,55],['STRONGMAN',300000,140],['ELITE',1500000,360],['CHAMPION',7500000,900],['HEAVYWEIGHT',40000000,2300],['TITAN',250000000,6000]
];
const missions=[['Do 500 Taps',500,'taps',50],['Reach Combo x50',50,'combo',75],['Upgrade Power 20 Times',20,'upgrades',100],['Earn 1,000,000 Power',1000000,'earned',150],['Play for 120 Minutes',120,'minutes',200]];
let s=JSON.parse(localStorage.getItem('ironRise10'))||{power:0,energy:100,maxEnergy:100,coins:0,gems:100,stage:1,taps:0,combo:0,bestCombo:0,upgrades:0,earned:0,minutes:0,claimed:{},ach:{},auto:false,last:Date.now()};
const $=id=>document.getElementById(id); const fmt=n=>n>=1e9?(n/1e9).toFixed(2)+'B':n>=1e6?(n/1e6).toFixed(2)+'M':n>=1e3?(n/1e3).toFixed(2)+'K':Math.floor(n).toString();
function save(){localStorage.setItem('ironRise10',JSON.stringify(s))}function stageCheck(){while(s.stage<10&&s.power>=stages[s.stage][1])s.stage++;}
function renderPath(){let h='';for(let i=0;i<20;i++){if(i<10){let st=stages[i];h+=`<div class="node ${i+1===s.stage?'active':''}"><b>${i+1} · ${st[0]}</b><img src="assets/characters/stage-${String(i+1).padStart(2,'0')}.png"></div>`}else h+=`<div class="node locked"><b>${i+1} · LOCKED</b><span class="soon">COMING SOON</span></div>`} $('path').innerHTML=h}
function render(){stageCheck();let st=stages[s.stage-1],prev=s.stage===1?0:stages[s.stage-2][1],pct=Math.min(100,((s.power-prev)/(st[1]-prev))*100);$('power').textContent=fmt(s.power);$('power2').textContent=fmt(s.power);$('energy').textContent=fmt(s.energy);$('energy2').textContent=`${fmt(s.energy)} / ${fmt(s.maxEnergy)}`;$('coins').textContent=fmt(s.coins);$('gems').textContent=fmt(s.gems);$('tapPower').textContent=fmt(st[2]);$('combo').textContent='x'+s.combo;$('crit').textContent=(5+Math.min(35,Math.floor(s.stage*3)))+'%';$('stageNum').textContent=s.stage;$('heroStage').textContent=s.stage;$('stageName').textContent=st[0];$('heroName').textContent=st[0];$('trainAmount').textContent=fmt(st[2]);$('stageBar').style.width=pct+'%';$('stageReq').textContent=`${fmt(Math.max(0,s.power-prev))} / ${fmt(st[1]-prev)} POWER`;$('character').src=`assets/characters/stage-${String(s.stage).padStart(2,'0')}.png`;$('autoBtn').className='toggle '+(s.auto?'on':'off');renderMissions();renderAchievements();renderPath();save()}
function train(){if(s.energy<=0){s.energy=Math.min(s.maxEnergy,s.energy+5);return}let st=stages[s.stage-1],crit=Math.random()<(5+Math.min(35,s.stage*3))/100;let gain=st[2]*(crit?2:1);s.power+=gain;s.earned+=gain;s.energy--;s.taps++;s.combo++;s.bestCombo=Math.max(s.bestCombo,s.combo);s.coins+=Math.max(1,Math.floor(gain/5));let f=$('float');f.textContent='+'+fmt(gain)+(crit?' CRIT!':'');f.classList.remove('show');void f.offsetWidth;f.classList.add('show');render()}
$('trainBtn').onclick=train;$('autoBtn').onclick=()=>{s.auto=!s.auto;render()};$('resetBtn').onclick=()=>{if(confirm('Reset all progress?')){localStorage.removeItem('ironRise10');location.reload()}};$('rewardBtn').onclick=()=>{s.coins+=1000;s.gems+=25;alert('Daily reward claimed: +1,000 coins and +25 gems!');render()};$('dailyBtn').onclick=()=>$('rewardBtn').click();$('upgradeBtn').onclick=()=>{let cost=100*Math.pow(2,s.upgrades);if(s.coins>=cost){s.coins-=cost;s.upgrades++;s.maxEnergy+=5;alert('Upgrade purchased!');render()}else alert('Not enough coins. Need '+fmt(cost)+'.')};$('trainingBtn').onclick=()=>alert('Training upgrades are tied to your stage. Keep grinding!');$('shopBtn').onclick=()=>alert('Shop coming in a future update.');$('settingsBtn').onclick=()=>alert('IRON RISE v1.0 — Autosave is ON. Stages 11–20 are COMING SOON.');
function renderMissions(){let h='';missions.forEach((m,i)=>{let val=m[2]==='taps'?s.taps:m[2]==='combo'?s.bestCombo:m[2]==='upgrades'?s.upgrades:m[2]==='earned'?s.earned:Math.floor(s.minutes);let done=val>=m[1],claimed=s.claimed[i];h+=`<div class="mission"><div class="missionTitle"><span>${m[0]}</span><b>+${m[3]}M</b></div><div class="missionBar"><i style="width:${Math.min(100,val/m[1]*100)}%"></i></div><div class="missionTitle"><small>${fmt(Math.min(val,m[1]))} / ${fmt(m[1])}</small><button class="claim" onclick="claimMission(${i})" ${!done||claimed?'disabled':''}>${claimed?'CLAIMED':'CLAIM'}</button></div></div>`});$('missions').innerHTML=h}
function claimMission(i){if(s.claimed[i])return;let m=missions[i];let val=m[2]==='taps'?s.taps:m[2]==='combo'?s.bestCombo:m[2]==='upgrades'?s.upgrades:m[2]==='earned'?s.earned:Math.floor(s.minutes);if(val>=m[1]){s.claimed[i]=1;s.power+=m[3]*1000000;render()}}
function renderAchievements(){let a=[['FIRST TAP',s.taps>=1],['POWER UP',s.upgrades>=1],['BIG GRIND',s.taps>=1000],['NO LIMIT',s.power>=1000000],['IRON WILL',s.bestCombo>=100]];$('achievements').innerHTML=a.map((x,i)=>`<div>🏆<br>${x[0]}<br><button onclick="claimAch(${i})" ${!x[1]||s.ach[i]?'disabled':''}>${s.ach[i]?'DONE':'CLAIM'}</button></div>`).join('')}
function claimAch(i){s.ach[i]=1;s.coins+=5000;render()}
setInterval(()=>{s.energy=Math.min(s.maxEnergy,s.energy+1);s.minutes+=1/60;if(s.auto&&s.energy>0)train();else render()},1000);render();
